name: WS1 workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello from WS1

      - name: Run a one-line script
        run: echo Hello again from WS1
        
      - run: echo ${{ github.event.client_payload }}
      - run: echo ${{ github.event.client_payload.ws1_test_string }}
      - run: echo ${{ github.event.client_payload.ws1_test_array }}
      
      - run: |
          sleep 25
          echo "For testing failure"
          exit 1



