name: WS1 workflow

on: 
  workflow_dispatch:
    inputs: 
      test_data:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello from WS1

      - name: Run a one-line script
        run: echo ${{ inputs.test_data }}
        
      - run: echo ${{ fromJSON(inputs.test_data) }}
      
      - run: |
          sleep 25
          echo "For testing failure"
          exit 1



